Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/LambdaCall:
  Enabled: false
